/* ============================================================
   QUIZ GAME v5.0.0 — ONLINE FOUNDATION
   Account identity, cloud adapter, sync queue and online-ready UI.
   ============================================================ */
(() => {
  "use strict";
  const KEY="quizGame_v500_online",CONFIG_KEY="quizGame_v500_config";
  const defaultData=()=>({version:1,playerId:crypto?.randomUUID?crypto.randomUUID():"guest-"+Date.now().toString(36),username:"Player",createdAt:new Date().toISOString(),lastSync:null,pending:[],connected:false});
  let data;try{data={...defaultData(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{data=defaultData()} if(!data.playerId)data.playerId=defaultData().playerId;
  const config=(()=>{try{return{apiBase:"",...JSON.parse(localStorage.getItem(CONFIG_KEY)||"{}")}}catch{return{apiBase:""}}})();
  const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
  function identityFromProfile(){try{const p=JSON.parse(localStorage.getItem("quizGame_profile")||"{}");if(p.name&&p.name!=="Player")data.username=String(p.name).slice(0,16)}catch{}}
  async function request(path,options={}){if(!config.apiBase)throw Error("No online backend configured");const r=await fetch(config.apiBase.replace(/\/$/,"")+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok)throw Error("HTTP "+r.status);return r.json().catch(()=>({}))}
  async function sync(){identityFromProfile();save();if(!config.apiBase){data.connected=false;save();render();return false}try{const result=await request("/players/sync",{method:"POST",body:JSON.stringify({playerId:data.playerId,username:data.username,pending:data.pending})});data.pending=[];data.lastSync=new Date().toISOString();data.connected=true;if(result.username)data.username=result.username;save();render();return true}catch{data.connected=false;save();render();return false}}
  function queue(type,payload){data.pending.push({id:Date.now()+Math.random(),type,payload,at:new Date().toISOString()});data.pending=data.pending.slice(-100);save()}
  function installStyle(){if(document.getElementById("onlineV500Style"))return;const s=document.createElement("style");s.id="onlineV500Style";s.textContent=`#onlineOverlay{position:fixed;inset:0;background:rgba(0,0,0,.72);display:none;align-items:center;justify-content:center;z-index:9999;padding:20px}#onlineOverlay.open{display:flex}.online-panel{width:min(620px,100%);max-height:90vh;overflow:auto;background:#0b1728;color:#eef6ff;border:1px solid #31516f;border-radius:22px;padding:24px;box-shadow:0 25px 80px rgba(0,0,0,.5)}.online-panel header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.online-panel header button{border:0;background:transparent;color:inherit;font-size:24px;cursor:pointer}.online-status{padding:12px;border-radius:12px;background:#07111f;margin-bottom:14px}.online-id{display:flex;gap:10px;align-items:center;background:#07111f;border-radius:12px;padding:12px;margin-bottom:14px}.online-id span{font-size:11px;opacity:.7}.online-id code{flex:1;overflow:hidden;text-overflow:ellipsis}.online-id button{cursor:pointer}.online-form{display:grid;gap:8px;margin-bottom:14px}.online-form label{display:grid;gap:6px;font-size:12px}.online-form input{padding:12px;border-radius:10px;border:1px solid #31516f;background:#07111f;color:#fff}.online-actions{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.online-notice{padding:14px;border-radius:14px;background:#10243a;border:1px solid #31516f}.online-notice p{font-size:13px;line-height:1.5;opacity:.8}.online-queue{display:flex;justify-content:space-between;margin-top:14px;padding-top:14px;border-top:1px solid #233b52}.online-btn{position:relative}.online-btn::after{content:"";position:absolute;right:8px;top:8px;width:7px;height:7px;border-radius:50%;background:#55d68a}.online-toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);z-index:10000}`;document.head.appendChild(s)}
  function build(){if(document.getElementById("onlineBtn"))return;installStyle();const actions=document.querySelector("#homeScreen .home-actions");if(!actions)return;const b=document.createElement("button");b.id="onlineBtn";b.className="shop-open-btn online-btn";b.textContent="🌐 ONLINE";actions.appendChild(b);const o=document.createElement("div");o.id="onlineOverlay";o.innerHTML=`<div class="online-panel"><header><div><div class="version">ONLINE • v5.0.0</div><h2>🌐 ONLINE HUB</h2></div><button id="onlineClose">✕</button></header><div class="online-status" id="onlineStatus"></div><div class="online-id"><span>PLAYER ID</span><code id="onlinePlayerId"></code><button id="copyPlayerId">COPY</button></div><div class="online-form"><label>USERNAME<input id="onlineUsername" maxlength="16"></label><button id="saveOnlineProfile" class="primary-btn">💾 SAVE IDENTITY</button></div><div class="online-actions"><button id="syncOnline" class="primary-btn">☁️ SYNC NOW</button><button id="exportOnline" class="secondary-btn">📦 EXPORT ONLINE PROFILE</button></div><div class="online-notice"><strong>ONLINE FOUNDATION</strong><p>Cloud synchronization is optional. The game remains fully playable offline. Configure an API endpoint later to enable shared accounts, global leaderboards and multiplayer services.</p></div><div class="online-queue"><span>PENDING SYNC</span><strong id="onlinePending">0</strong></div></div>`;document.body.appendChild(o);b.onclick=()=>{identityFromProfile();render();o.classList.add("open")};document.getElementById("onlineClose").onclick=()=>o.classList.remove("open");document.getElementById("syncOnline").onclick=async()=>{const ok=await sync();toast(ok?"☁️ Cloud sync complete":"📡 Offline mode — sync queued")};document.getElementById("saveOnlineProfile").onclick=()=>{const name=document.getElementById("onlineUsername").value.trim();if(name)data.username=name.slice(0,16);queue("identity",{username:data.username});render();toast("👤 Online identity saved")};document.getElementById("copyPlayerId").onclick=async()=>{try{await navigator.clipboard.writeText(data.playerId);toast("📋 Player ID copied")}catch{}};document.getElementById("exportOnline").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="quiz-game-online-profile.json";a.click();URL.revokeObjectURL(a.href)};render()}
  function render(){const id=document.getElementById("onlinePlayerId");if(!id)return;identityFromProfile();id.textContent=data.playerId;document.getElementById("onlineUsername").value=data.username;document.getElementById("onlinePending").textContent=data.pending.length;document.getElementById("onlineStatus").textContent=data.connected?"🟢 CONNECTED":(config.apiBase?"🟠 OFFLINE / RETRY AVAILABLE":"⚪ OFFLINE-FIRST MODE")}
  function toast(message){let e=document.getElementById("onlineToast");if(!e){e=document.createElement("div");e.id="onlineToast";e.className="online-toast";document.body.appendChild(e)}e.textContent=message;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("show"),2600)}
  function upgradeVersionUI(){document.title="Quiz Game v5.0.0";document.querySelector('meta[name="description"]')?.setAttribute("content","Quiz Game v5.0.0 — Online Foundation.");const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue.includes("v4.0.0"))n.nodeValue=n.nodeValue.replaceAll("v4.0.0","v5.0.0");if(n.nodeValue.includes("VERSION 4.0.0"))n.nodeValue=n.nodeValue.replaceAll("VERSION 4.0.0","VERSION 5.0.0")})}
  window.QuizOnline={get data(){return data},sync,queue,configure(apiBase){config.apiBase=String(apiBase||"").trim();localStorage.setItem(CONFIG_KEY,JSON.stringify(config));render()},isConfigured:()=>Boolean(config.apiBase)};
  identityFromProfile();save();const boot=setInterval(()=>{if(document.readyState!=="loading"){clearInterval(boot);upgradeVersionUI();build()}},100);
})();
