const PROFILE_KEY="quizGame_v006_profile";
const PROFILE_DEFAULT={name:"Player",avatar:"🎮"};
const PROFILE_AVATARS=["🎮","😎","🧠","🔥","⚡","👑","🚀","💎"];
function getProfile(){try{return {...PROFILE_DEFAULT,...JSON.parse(localStorage.getItem(PROFILE_KEY)||"{}")}}catch(e){return {...PROFILE_DEFAULT}}}
function saveProfile(p) {localStorage.setItem(PROFILE_KEY,JSON.stringify({name:String(p.name||"Player").trim().slice(0,16)||"Player",avatar:PROFILE_AVATARS.includes(p.avatar)?p.avatar:"🎮"}))}
function renderProfile(){const p=getProfile(),xp=typeof getXP==="function"?getXP():0,level=typeof getLevel==="function"?getLevel(xp):1,rank=typeof getRank==="function"?getRank(level):"NEWCOMER",games=typeof getGamesPlayed==="function"?getGamesPlayed():0,hs=typeof getHighScore==="function"?getHighScore():0,ach=typeof getUnlockedAchievements==="function"?getUnlockedAchievements().length:0,coins=typeof getCoins==="function"?getCoins():0,items=typeof getOwnedItems==="function"?getOwnedItems().length:0;$("profileAvatar").textContent=p.avatar;$("profileName").textContent=p.name;$("profileLevel").textContent=level;$("profileRank").textContent=rank;$("profileXP").textContent=level>=100?"MAX LEVEL":`${xp%500} / 500 XP`;$("profileXPBar").style.width=typeof getXPPercent==="function"?`${getXPPercent(xp)}%`:"0%";$("profileGames").textContent=games;$("profileHighScore").textContent=hs;$("profileAchievements").textContent=`${ach}/${typeof ACHIEVEMENTS!=="undefined"?ACHIEVEMENTS.length:10}`;$("profileCoins").textContent=coins;$("profileItems").textContent=items;$("profileNameInput").value=p.name;$("avatarChoices").innerHTML=PROFILE_AVATARS.map(a=>`<button class="avatar-choice ${a===p.avatar?"selected":""}" data-avatar="${a}">${a}</button>`).join("")}
function openProfile(){renderProfile();document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$("profileScreen").classList.add("active")}
function closeProfile(){if(typeof updatePlayerUI==="function")updatePlayerUI();document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$("homeScreen").classList.add("active")}
function injectProfileStyles(){const style=document.createElement("style");style.textContent=`.home-actions{display:flex;gap:10px;margin-bottom:14px}.home-actions>.shop-open-btn{flex:0 0 auto}.home-actions>.coin-panel{flex:1;margin:0}.profile-card{max-width:760px;margin:auto;padding:28px;background:linear-gradient(145deg,rgba(19,36,59,.96),rgba(8,20,35,.96));border:1px solid rgba(255,255,255,.09);border-radius:24px;box-shadow:0 25px 70px rgba(0,0,0,.35)}.profile-top{display:flex;align-items:center;gap:18px;margin:20px 0}.profile-avatar{width:82px;height:82px;display:grid;place-items:center;border-radius:22px;background:#0b192b;border:1px solid rgba(85,214,190,.3);font-size:3rem}.profile-title h2{margin:0;font-size:2rem}.profile-title p{margin:6px 0;color:#9eacc0}.profile-rank{color:#55d6be!important;font-weight:900;letter-spacing:1px}.profile-xp{padding:16px;border-radius:15px;background:rgba(85,214,190,.06);border:1px solid rgba(255,255,255,.09);margin-bottom:16px}.profile-xp-line{display:flex;justify-content:space-between;color:#9eacc0;font-size:.78rem;margin-bottom:8px}.profile-track{height:9px;background:#17283d;border-radius:999px;overflow:hidden}.profile-bar{height:100%;width:0;background:#55d6be}.profile-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.profile-stat{padding:16px;text-align:center;border:1px solid rgba(255,255,255,.09);border-radius:15px;background:#0b192b}.profile-stat strong{display:block;font-size:1.35rem}.profile-stat span{display:block;color:#9eacc0;font-size:.68rem;letter-spacing:.8px;margin-top:5px}.profile-section{margin-top:22px}.profile-section h3{font-size:.85rem;letter-spacing:1px}.profile-input{width:100%;padding:13px;border-radius:12px;border:1px solid rgba(255,255,255,.1);background:#0b192b;color:#f5f7fb;outline:none}.avatar-choices{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.avatar-choice{width:48px;height:48px;border-radius:12px;border:1px solid rgba(255,255,255,.09);background:#0b192b;font-size:1.5rem;cursor:pointer}.avatar-choice.selected{border-color:#55d6be;background:rgba(85,214,190,.12)}.profile-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.danger-btn{width:100%;border:1px solid rgba(255,107,122,.3);border-radius:14px;padding:13px;background:rgba(255,107,122,.07);color:#ff8b97;font-weight:900;cursor:pointer}@media(max-width:620px){.home-actions{flex-direction:column}.profile-card{padding:20px 15px}.profile-stats{grid-template-columns:1fr 1fr}.profile-avatar{width:68px;height:68px;font-size:2.4rem}.profile-title h2{font-size:1.6rem}.profile-actions{grid-template-columns:1fr}}`;document.head.appendChild(style)}
function setupProfile(){injectProfileStyles();$("profileBtn").addEventListener("click",openProfile);$("closeProfileBtn").addEventListener("click",closeProfile);$("avatarChoices").addEventListener("click",e=>{const b=e.target.closest("[data-avatar]");if(!b)return;document.querySelectorAll(".avatar-choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("saveProfileBtn").addEventListener("click",()=>{const b=document.querySelector(".avatar-choice.selected");saveProfile({name:$("profileNameInput").value,avatar:b?b.dataset.avatar:"🎮"});renderProfile();if(typeof updatePlayerUI==="function")updatePlayerUI()});$("resetProfileBtn").addEventListener("click",()=>{if(!confirm("Đặt lại tên và avatar về mặc định? Dữ liệu game sẽ không bị xóa."))return;saveProfile(PROFILE_DEFAULT);renderProfile()});renderProfile()}
document.addEventListener("DOMContentLoaded",setupProfile);
