const QUESTIONS_PER_GAME=10,QUESTION_TIME=15,SCORE_PER_CORRECT=100,COMBO_BONUS_STEP=25,MAX_COMBO_MULTIPLIER=3,SPEED_BONUS_MAX=50,XP_PER_CORRECT=25,XP_PER_GAME=20,XP_SPEED_BONUS=5,XP_COMBO_BONUS=5,XP_PER_LEVEL=500,MAX_LEVEL=100;
const HIGH_SCORE_KEY="quizGame_v003_highScore",XP_KEY="quizGame_v003_xp";
const state={category:"all",questions:[],current:0,score:0,correct:0,wrong:0,combo:0,bestCombo:0,bonusScore:0,earnedXP:0,timeLeft:QUESTION_TIME,timerId:null,locked:false,levelBeforeGame:1};
const $=id=>document.getElementById(id),screens={home:$("homeScreen"),quiz:$("quizScreen"),result:$("resultScreen")},categoryButtons=document.querySelectorAll(".category-btn");
function showScreen(n){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[n].classList.add("active")}
function getXP(){return Number(localStorage.getItem(XP_KEY)||0)} function setXP(x){localStorage.setItem(XP_KEY,String(Math.max(0,x)))}
function getLevel(x=getXP()){return Math.min(MAX_LEVEL,Math.floor(x/XP_PER_LEVEL)+1)} function getLevelXP(x=getXP()){return x%XP_PER_LEVEL}
function getRank(l){if(l>=50)return"LEGEND";if(l>=30)return"MASTER";if(l>=20)return"EXPERT";if(l>=10)return"VETERAN";if(l>=5)return"SKILLED";return"NEWCOMER"}
function getHighScore(){return Number(localStorage.getItem(HIGH_SCORE_KEY)||0)} function getXPPercent(x=getXP()){return getLevel(x)>=MAX_LEVEL?100:getLevelXP(x)/XP_PER_LEVEL*100}
function updatePlayerUI(){const x=getXP(),l=getLevel(x),lx=getLevelXP(x);$("homeLevel").textContent=l;$("homeXPText").textContent=l>=MAX_LEVEL?`${XP_PER_LEVEL} / ${XP_PER_LEVEL} XP`:`${lx} / ${XP_PER_LEVEL} XP`;$("homeRank").textContent=getRank(l);$("homeXPBar").style.width=`${getXPPercent(x)}%`;$("homeHighScore").textContent=getHighScore()}
function updateQuizPlayerUI(){$("quizLevel").textContent=getLevel();$("quizXP").textContent=getXP()}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function prepareQuestions(){let p=state.category==="all"?QUESTION_BANK:QUESTION_BANK.filter(q=>q.category===state.category);if(p.length<QUESTIONS_PER_GAME)p=[...p,...QUESTION_BANK.filter(q=>!p.includes(q))];state.questions=shuffle(p).slice(0,QUESTIONS_PER_GAME)}
function startGame(){clearInterval(state.timerId);state.current=0;state.score=0;state.correct=0;state.wrong=0;state.combo=0;state.bestCombo=0;state.bonusScore=0;state.earnedXP=0;state.locked=false;state.levelBeforeGame=getLevel();prepareQuestions();$("score").textContent="0";updateQuizPlayerUI();updateComboDisplay();showScreen("quiz");renderQuestion()}
function renderQuestion(){clearInterval(state.timerId);state.locked=false;state.timeLeft=QUESTION_TIME;const q=state.questions[state.current];$("questionNumber").textContent=`${state.current+1}/${QUESTIONS_PER_GAME}`;$("questionText").textContent=q.question;$("categoryLabel").textContent=CATEGORY_NAMES[q.category]||"QUIZ";$("feedback").textContent="";$("timer").textContent=state.timeLeft;$("timer").parentElement.classList.remove("warning");$("progressBar").style.width=`${state.current/QUESTIONS_PER_GAME*100}%`;updateComboDisplay();updateQuizPlayerUI();const letters=["A","B","C","D"],answers=$("answers");answers.innerHTML="";q.answers.forEach((a,i)=>{const b=document.createElement("button");b.className="answer-btn";b.innerHTML=`<span class="answer-letter">${letters[i]}</span><span>${a}</span>`;b.addEventListener("click",()=>chooseAnswer(i,b));answers.appendChild(b)});startTimer()}
function startTimer(){state.timerId=setInterval(()=>{state.timeLeft--;$("timer").textContent=state.timeLeft;if(state.timeLeft<=5)$("timer").parentElement.classList.add("warning");if(state.timeLeft<=0){clearInterval(state.timerId);handleTimeout()}},1000)}
function disableAnswers(){document.querySelectorAll(".answer-btn").forEach(b=>b.disabled=true)} function getComboMultiplier(){if(state.combo>=6)return 3;if(state.combo>=4)return 2;if(state.combo>=2)return 1.5;return 1} function calculateSpeedBonus(){return Math.min(SPEED_BONUS_MAX,state.timeLeft*4)} function calculateComboBonus(){return state.combo<2?0:Math.round(COMBO_BONUS_STEP*Math.min(state.combo,6))}
function updateComboDisplay(){$("comboCount").textContent=state.combo;$("comboMultiplier").textContent=`x${getComboMultiplier()}`}
function addScore(base,speed,combo){const m=getComboMultiplier(),mb=Math.round(base*m),g=mb+speed+combo;state.score+=g;state.bonusScore+=speed+combo+(mb-base);$("score").textContent=state.score;return{gained:g,multiplier:m}}
function grantXP(amount){const old=getXP(),next=Math.min(MAX_LEVEL*XP_PER_LEVEL-1,old+amount);setXP(next);state.earnedXP+=next-old;return getLevel(next)}
function chooseAnswer(index,selected){if(state.locked)return;state.locked=true;clearInterval(state.timerId);disableAnswers();const q=state.questions[state.current],buttons=document.querySelectorAll(".answer-btn");if(index===q.correct){selected.classList.add("correct");state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);const speed=calculateSpeedBonus(),combo=calculateComboBonus(),r=addScore(SCORE_PER_CORRECT,speed,combo);let xp=XP_PER_CORRECT;if(speed>=30)xp+=XP_SPEED_BONUS;if(state.combo>=3)xp+=XP_COMBO_BONUS;grantXP(xp);let t=`✓ Chính xác! +${r.gained} điểm • +${xp} XP`;if(r.multiplier>1)t+=` • Combo x${r.multiplier}`;if(speed>0)t+=` • Tốc độ +${speed}`;if(combo>0)t+=` • Combo bonus +${combo}`;$("feedback").textContent=t}else{selected.classList.add("wrong");buttons[q.correct].classList.add("correct");state.wrong++;state.combo=0;$("feedback").textContent=`✗ Sai! Combo bị reset. Đáp án đúng: ${q.answers[q.correct]}`}updateComboDisplay();updateQuizPlayerUI();nextQuestionAfterDelay()}
function handleTimeout(){if(state.locked)return;state.locked=true;disableAnswers();const q=state.questions[state.current],b=document.querySelectorAll(".answer-btn");b[q.correct].classList.add("correct");state.wrong++;state.combo=0;$("feedback").textContent=`⏰ Hết giờ! Combo bị reset. Đáp án: ${q.answers[q.correct]}`;updateComboDisplay();nextQuestionAfterDelay()}
function nextQuestionAfterDelay(){setTimeout(()=>{state.current++;state.current>=QUESTIONS_PER_GAME?finishGame():renderQuestion()},1100)}
function finishGame(){clearInterval(state.timerId);$("progressBar").style.width="100%";const accuracy=Math.round(state.correct/QUESTIONS_PER_GAME*100),oldHigh=getHighScore(),isRecord=state.score>oldHigh;grantXP(XP_PER_GAME);if(isRecord)localStorage.setItem(HIGH_SCORE_KEY,String(state.score));const xp=getXP(),level=getLevel(xp),levelUp=level>state.levelBeforeGame;$("finalScore").textContent=state.score;$("correctCount").textContent=state.correct;$("wrongCount").textContent=state.wrong;$("accuracy").textContent=`${accuracy}%`;$("bestCombo").textContent=state.bestCombo;$("earnedXP").textContent=`+${state.earnedXP}`;$("resultLevel").textContent=level;$("resultXPText").textContent=level>=MAX_LEVEL?`${XP_PER_LEVEL} / ${XP_PER_LEVEL} XP`:`${getLevelXP(xp)} / ${XP_PER_LEVEL} XP`;$("resultRank").textContent=getRank(level);$("resultXPBar").style.width=`${getXPPercent(xp)}%`;$("levelUpMessage").innerHTML=levelUp?`🎉 <strong>LEVEL UP!</strong> Bạn đã lên Level ${level}!`:`⭐ Cấp hiện tại: <strong>${level}</strong>`;$("recordMessage").textContent=isRecord&&state.score>0?"🎉 Kỷ lục mới!":`Kỷ lục: ${Math.max(oldHigh,state.score)} điểm`;$("resultMessage").textContent=accuracy===100?"Hoàn hảo! Bạn không bỏ lỡ câu nào.":accuracy>=70?"Rất tốt! Hãy giữ combo để kiếm nhiều điểm và XP hơn.":accuracy>=50?"Không tệ! Tiếp tục luyện tập để lên cấp.":"Hãy luyện tập thêm và chinh phục quiz nhé!";updatePlayerUI();showScreen("result")}
categoryButtons.forEach(b=>b.addEventListener("click",()=>{categoryButtons.forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.category=b.dataset.category}));$("startBtn").addEventListener("click",startGame);$("playAgainBtn").addEventListener("click",startGame);$("homeBtn").addEventListener("click",()=>{clearInterval(state.timerId);updatePlayerUI();showScreen("home")});updatePlayerUI();
